version: '3.8'

services:
  # Development API with hot reload
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai_intern_api_dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=True
      - ENVIRONMENT=development
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - ai_intern_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Database
  db:
    image: postgres:15-alpine
    container_name: ai_intern_db_dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ai_intern_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: ai_intern_redis_dev
    ports:
      - "6379:6379"
    networks:
      - ai_intern_network

volumes:
  postgres_dev_data:

networks:
  ai_intern_network:
    driver: bridge
